### ISSUE TITLE
Remove instructions for installing Docker locally

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#126]
- We can point to the docker website. If we don’t cover it it won’t get out of date _and_ it won’t look like its our fault that the software doesn’t work.
- If anything, focus on how users can develop using our tools
- I, like many others, have a Windows-based machine. It appears that Docker only works with Windows 10 Pro/Enterprise/Education. I have Windows 7. Strangely, you can run on Macs that are as old as 2010. What are you expecting people to do in this situation? Are we expecting everyone to be running this, or a Linux / OSX machine? Am I able to use Docker Toolbox?

**Comment by rachelshekar** [comment]
Where is the docker text in https://www.gitbook.com/book/terraref/terraref-documentation/details?
What is the docker website link?

**Comment by dlebauer** [comment]
I think the tutorials for setting up docker are linked from https://terraref.gitbooks.io/terraref-documentation/content/developing-clowder-extractors.html

Some of the links are broken ...

**Comment by jdmaloney** [comment]
- I agree, instructions to install Docker should point to their webpage (though I don't see where we reference this in documentation; my search for Docker didn't turn up anything relevant to installing it)
- Agree
- Windows was slow to the Docker train and since Linux/OS X are built upon UNIX/BSD (which is the world Docker was developed in) they inherently have had native support for a while.  Folks not running Windows 10 could spin up a VM in Virtual Box/VMWare Fusion/etc. to run Linux.

I feel like @max-zilla should be in on this as he is the man using Docker for things.

**Comment by dlebauer** [comment]
These were either removed or Justin was referring to the links on this page.

@harshagrawal28 could you please review / update the [Clowder documentation](https://github.com/terraref/documentation/edit/master/developing-clowder-extractors.md) based on the process that you just went through?
