### ISSUE TITLE
Please document converting geographic coordinate systems

### ISSUE THREAD

**Issue by czender** [terraref/documentation#7]
### updated description

* currently there are two pages: 
  * https://github.com/terraref/documentation/blob/version1/geographic-coordinate-data.md
  * https://github.com/terraref/documentation/blob/version1/spatial-reference-system-data.md

need to describe the multiple coordinate reference systems at Maricopa

There is a lot of confusing content in these related issues:
- Convert gantry coordinate system from right handed (x positive to left) to conventional (x positive to right)  https://github.com/terraref/computing-pipeline/issues/109
- converting lemnatec scanner metadata to geographic positions https://github.com/terraref/reference-data/issues/32
- Create polygons for sites table in BETYdb https://github.com/terraref/computing-pipeline/issues/174
- Create custom spatial reference systems for PostGIS https://github.com/terraref/reference-data/issues/51
- point cloud origin (@ssolmazhajmohammadi) https://github.com/terraref/reference-data/issues/44
- georeferencing hyperspectral data https://github.com/terraref/computing-pipeline/issues/144
- Store location and field of view metadata associated with each file in Clowder https://github.com/terraref/computing-pipeline/issues/101
- A protocol for checking that scans align with plots https://github.com/terraref/computing-pipeline/issues/153

---
### original issue

How do we (@hmb1 and @FlyingWithJerome) convert position on a gantry sensor to geographic location?

For example, this file
[$DATA/terraref/MovingSensor/SWIR/2016-03-05/2016-03-05__10-08_49_485/e2eaa60d-9f3d-4af9-9fe0-8f01731b70d5_metadata.json](https://gist.github.com/dlebauer/b47218fc842e1e2bb46a)
contains these metadata:

``` json
"gantry_system_variable_metadata": {
      "Time": "03/05/2016 10:08:49",
      "Position x [m]": "195.1725",
      "Position y [m]": "7.95",
      "Position z [m]": "0.599",
```

Where "exactly" is x=y=z=0.0 and what approach should we use to convert offsets from that origin to absolute geographic location (lat/lon)? And, for imagery, how do we determine the location of each pixel (Sample and line in ENVI-speak) in (x,y,z) coordinates within the image whose nominal position is described (I assume) by x,y,z above?

A worked-through example would be tremendously helpful.

Thanks!
Charlie

**Comment by nfahlgren** [comment]
Hi all,

@solmazhajmohammadi and I were just talking about this this morning. I cannot remember, but does the gantry have a GPS system in addition to the xyz positioning system? If not, what do you all think about the possibility of putting georeferenced markers across the field (now or before sorghum planting) and using them to calibrate the xyz system? I think Solmaz has some ideas about what kind of markers we might be able to use (potentially make) for both this purpose and for camera calibration/testing.

**Comment by dlebauer** [comment]
**where is the sensor**?

[0,0,0] is the SW corner of the gantry system. The [x,y,z] you give is the location of a reference point on the camera box. In addition to the location of the camera box, we need the [x,y,z] offset of the specific sensor relative to the camera box reference point.

@rjstrand may be able to provide some guidance (and perhaps the actual coordinates) of each sensor within the camera box

@pless, @ejdelp33 may also have some suggestions

**Comment by dlebauer** [comment]
There is an additional section in the metadata file with relevant fields ... some currently unused, and we probably need to add a field for `"location in camera box Z [m]",` 

```json
    "sensor_fixed_metadata": {
      "sensor manufacturer": "Headwall Scientific",
      "sensor product name": "SWIR",
      "sensor serial number": "Todo",
      "sensor description": "Todo",
      "sensor purpose": "Todo",
      "location in gantry system": "camera box, facing ground",
      "location in camera box X [m]": "Todo",
      "location in camera box Y [m]": "Todo",
      "optics manufactuer": "Stingray optics",
      "optics name": "SR-1200-030 F/1.3 0.48-2.5um",
      "optics focal length [mm]": "25",
      "optics focus apperture": "2.0",
      "Output data format": "hypercube with preview image and additional information provided by sensor",
      "Calibration available": "todo, mail to bob"
    },
```

I've pasted the entire metadata file here: https://gist.github.com/dlebauer/b47218fc842e1e2bb46a

**Comment by dlebauer** [comment]
@rjstrand just provided approximate field coordinates (from his cell phone GPS)

> Here are locations from my cell phone. There is a little noise in it. Additionally, the north readings could be off a bit because there was a big chunk of metal in the way...  ;)

> -Bob

> SE Corner     33° 04.470' N / -111° 58.485' W
SW Corner.   33° 04.474' N / -111° 58.505' W
NW Corner.   33° 04.592' N / -111° 58.505' W
NE Corner.   33° 04.591' N / -111° 58.487' W

The SW Corner is the [0,0] local reference point so that North and East are positive.

**Comment by solmazhajmohammadi** [comment]
To determine the location of each pixel within the image, Extrinsic and Intrinsic calibration matrices are needed.
3 coordinate systems exist: 
- Field coordinate frame (Xf , Yf , Zf)
- Camera coordinate (Xc , Yc , Zc)
- Image coordinate (Xp , Yp)

1 ) Extrinsic calibration matrix: 
The extrinsic calibration parameters specify the transformation from the field to the camera coordinates, and it is represented as,
[Xc  Yc  Zc]T=** Ro**  [Xf  Yf  Zf]'+ **to**
Since there is no rotation (**Ro**), MEXis only translating vector to. to is transition vector from the control point (0,0,0) to camera position [Xc Yc Zc]. Considering that gantry is moving with constant speed (Vx) in x direction , and metadata information shows the starting time and start position of a scan.  
**to** = [+xg+Vx*(ts-tf)   +yg   +zg]'  

Where (xg,yg,zg) is the camera position in gantry box. For Hyperspectral camera (xg,yg,zg) is (1.9 , 0.855 , 0.635). **t**s is the start time and tf is the scanned time for the specific line. 
For examplw,  (x,y,z) =(195.1725,7.95,0.599) described in metadata, camera position is ( 197.0725, 8.805,  1.234). 

2 ) Intrinsic calibration matrix: 
The intrinsic calibration parameters specify the transformation from the camera coordinate to the pixel coordinates.
Notes:
- The geometric distortions that exist between the 272 bands are considered to be small. 
- No rectification is done. 
- No distortion and lens model is considered.
- Mirror angle change is not considered. 
Generally nothing special about hyperspectral camera is included in this calculation. I have contacted the Headwall support group, and they will provide me with calibration information soon. Then, I will able to update the intrinsic calibration matrix. For a simple case:

Coordinate transformation between camera plane and image plane:

[Xp Yp f]'= **Min**[I  0] [Xc  Yc  Zc]'

Simple orientation matrix is:

  **Min**: 
f/p    0     lx
                0     f/p    ly
                0      0      1
lx and ly is the center of image. f is focal length, and p represents pixel pitch. 
For example:

**Comment by dlebauer** [comment]
@solmazhajmohammadi not sure why this was closed, but I don't think it has been resolved.

**Comment by TinoDornbusch** [comment]
We will provide reference coordinates this week gantry coordinates <>GPS. Mathematically two are enough, but we will do more. Is that enough for you to derive the transformation matrix / look-up table?

**Comment by solmazhajmohammadi** [comment]
I accidentally closed this one, and reopen it here: 
https://github.com/terraref/documentation/issues/9
For hyperspectral data, I think using external trigger is the best approach to convert the pixel positions to the GPS/Gantry coordinate system.  
For converting only gantry's location to geographic location, we have not had GPS location of (0,0). 
However, I think it would be more accurate to use only gantry coordinate system, instead of recording rail temperature and modelling the location based on the temperature change.

**Comment by solmazhajmohammadi** [comment]
In a case you need initial conversion matrix between GPS and Gantry Location you can use : Gantry_Location=S * GPS  
(Note: it is an initial linear model, and might have up to 5 cm error)
Linear modelling between GPS coordinate and Gantry location:

Gantry_Location=[ Gantry_y ; Gantry_x]

GPS=[ Lon ; Lat ; 1]

S =[
   -93.5378801063054e+003    0.00000000000000e+000   -10.4738844723827e+006
    0.00000000000000e+000    110.853602042202e+003   -3.66643212115991e+006]


Gantry_Location=S * GPS

**Comment by solmazhajmohammadi** [comment]
Swir data with external trigger "ON" in the metadata, should be corrected. Pixel dimension is 1mm in the long axis and between 1-2mm in the short axis depends on the working distance.
I took a quick look at the data, I guess the setting has not been changed in the metadata. @smarshall-bmr can you please make sure that  the "sensor_variable_metadata" is corrected before the new scans.

**Comment by rachelshekar** [comment]
Documentation  https://github.com/terraref/documentation/blob/version1/geographic-coordinate-data.md

**Comment by max-zilla** [comment]
https://terraref.gitbooks.io/terraref-documentation/content/user/geospatial-information.html

Conversion methods are described in detail here.
