### ISSUE TITLE
Meterological Data product creation

### ISSUE THREAD

**Issue by rachelshekar** [terraref/documentation#87]
https://github.com/terraref/documentation/blob/master/user/meteorological-data.md

**Comment by Zodiase** [comment]
Is this documentation supposed to explain how the raw data is being created? The extractor I wrote only processes data files uploaded by whatever source and I have no idea how those files are created in the first place.

**Comment by dlebauer** [comment]
@Andrade-Pedro can you provide documentation of the weather station? Location, sensors, etc?

**Comment by dlebauer** [comment]
@Zodiase From https://github.com/terraref/reference-data/issues/48


will need to be revised / flushed out, 

 @jtheun can you help with documentation? Also, we are missing location and height 

This is from your prev. email and terraref/reference-data#48
This is what the raw data stream looks like: The top row can be ignored. The second header row contains column information: 

* Timestamp - date and time the measurement was made.
* Record - the record number/measurement number since the current program was started.
* BattV - battery voltage of the station.
* PTemp_C - panel temperature of the data logger. Internal temperature, in degrees Celcius.
* AirTC - Outside air temperature, Celcius. Vaisala HMP60 humidity and temperature probe.
* RH - relative humidity, percent. Inside the same probe with temperature sensor (HMP60).
* Pyro - LI-COR pyranometer, model LI-200. Output in watts/m^-2. 
* PAR_ref - LI-COR quantum sensor, model LI-190. Output in micro mols per second-meter^2.
* WindDir - Gill Instruments WindSonic 2-Axis anemometer. Wind direction (degrees relative to true north).
* WS_ms - same instrument as above, wind speed in meters per second.
* Rain_mm_Tot - Texas Electronics rain bucket, model TE525. Output is counts, 1 millimeter of rain per count.

Custom calibration coefficients are applied at the time of the measurement to convert raw signals into the physical units in the logged record. They were derived during factory calibration and are listed on the sensors' data sheet.

**Comment by Zodiase** [comment]
I've added documentation about what the extractor does.
